CREATE SEQUENCE LOGIN_ATTEMPT_SEQ
	START WITH 1 
	INCREMENT BY 1 
	NO MAXVALUE
;

CREATE TABLE LOGIN_ATTEMPT (
	ID BIGINT NOT NULL DEFAULT NEXTVAL('LOGIN_ATTEMPT_SEQ'),
	USERNAME	VARCHAR(255) NOT NULL,
	PASSWD		VARCHAR(255) NOT NULL,
	IP_ADDRESS	VARCHAR(255) DEFAULT NULL,
	ATTEMPT_TIME	BIGINT NOT NULL,
	ADDED_TS	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MODIFIED_TS	TIMESTAMP	
);

ALTER TABLE LOGIN_ATTEMPT ADD CONSTRAINT PK_LOGIN_ATTEMPT PRIMARY KEY (ID)
;

CREATE OR REPLACE FUNCTION UPDATE_PROC() RETURNS TRIGGER AS $BODY$
    BEGIN
	IF (TG_OP = 'UPDATE') THEN
	      SELECT CURRENT_TIMESTAMP INTO NEW.MODIFIED_TS;
	END IF;
	RETURN NEW;
    END;
$BODY$ LANGUAGE plpgsql;


CREATE TRIGGER LOGIN_ATTEMPT_UPD_TRG
 BEFORE UPDATE ON LOGIN_ATTEMPT
 FOR EACH ROW EXECUTE PROCEDURE UPDATE_PROC();
 
 
 
 
drop TABLE LOGIN_ATTEMPT; 
drop SEQUENCE LOGIN_ATTEMPT_SEQ;
